### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by subu1979** [BinaryKits/ZPLUtility#10]
Not able to download the file from below link

https://www.zebra.com/content/dam/zebra/manuals/en-us/software/zpl-zbi2-pm-en.pdf

**Comment by YipingRuan** [comment]
Yes, even google search result is pointing to 404.
try this: [https://github.com/robmachado/webetiq/blob/master/local/Doc/zpl-zbi2-pm-en.pdf](https://github.com/robmachado/webetiq/blob/master/local/Doc/zpl-zbi2-pm-en.pdf)

**Comment by subu1979** [comment]
Thank you
