### ISSUE TITLE
Generated Qr Code missing first Letter

### ISSUE THREAD

**Issue by zmp2000** [BinaryKits/ZPLUtility#12]
Hi, using the default QrCode element generates a Qr that misses the first letter
example:

`LabelElements.Add(new ZPLQRCode("ACP001", 10, 20,2, 10));`

The Generated QrCode is "CP001"
And the Zpl Line responsible is ^FDQM,ACP001^FS

Note that the default ErrorCorrection Q is present followed by the Data Input "M" which should be  "A" to correct the problem

**Comment by YipingRuan** [comment]
@zmp2000 Help verify https://www.nuget.org/packages/ZPLUtility/1.4.0
