### ISSUE TITLE
Adding images to ZPL

### ISSUE THREAD

**Issue by Karthik-Nagendiran** [BinaryKits/ZPLUtility#2]
Hi,
How do I add an Image (base64 encoded string) to the ZPL using your utility ?
Basically the scenario is like, the user will upload an image and I will convert them to base64 encoded string and that image needs to be printed through ZPL commands on the label.
Any suggestions ?
thanks,
Karthik. N

**Comment by YipingRuan** [comment]
Thanks for your feedback. 
At this moment you need to prepare the raw ZPL code:
`renderEngine.Add(new ZPLRaw("~DGd:o.x,t,w,data"));`

I am thinking a good way to allow jpg image directly, do you have any suggestions?

**Comment by Karthik-Nagendiran** [comment]
I'm currently using ~DYE command to process the Image data. Converting the image data to Bytes and then to ASCII HEX. But sometimes it is taking too much of time for the conversion. Looking for better alternatives.

**Comment by YipingRuan** [comment]
How about something like this:
[http://www.jcgonzalez.com/zpl-ascii-hex-representation-image-generator](url)

Given a image stream and monochrome ZPL code is generated.

**Comment by YipingRuan** [comment]
Try the new commit
[https://github.com/BinaryKits/ZPLUtility/commit/519c89f21868edec9c1c4a5da3b0f4625d17dafb](https://github.com/BinaryKits/ZPLUtility/commit/519c89f21868edec9c1c4a5da3b0f4625d17dafb)

**Comment by Karthik-Nagendiran** [comment]
Thanks for the update. Anyway to disable the scaling of image alone when I give source and target DPI.

**Comment by YipingRuan** [comment]
Do you mean the physical dimensions on the label  should remain the same regardless of dpi?

**Comment by Karthik-Nagendiran** [comment]
Yes, When I tried your code to process the image, after scaling the image size seems to be bigger whereas the texts are scaled properly and fitting into the Label dimension.

**Comment by Karthik-Nagendiran** [comment]
How can I convert the image to Gray scale instead of Black and White ? Because converting it to Black and White loses the image quality and the contents are also not clear.

**Comment by YipingRuan** [comment]
okay let me combine those. Takes sometime I am traveling

**Comment by YipingRuan** [comment]
Due to the nature of ZPL printer (black and white dots only, no gray scale), we need to apply "Halftone" or "Dithering" to the original image. http://paint.net.amihotornot.com.au/Features/Effects/Plugins/Render/Dither/

This is an image process issue and should be done in Photoshop or Paint.net, as it requires many parameters.
