### ISSUE TITLE
BinaryKits.ZPLUtility.TestConsole.cs generated "preview.png" is inverted

### ISSUE THREAD

**Issue by YipingRuan** [BinaryKits/ZPLUtility#20]
Is this intentional by https://github.com/BinaryKits/ZPLUtility/blob/c2b8b9062d21b7515551f36248a73efd239ab38a/src/BinaryKits.ZPLUtility.TestConsole.cs/Program.cs#L19 ?

![image](https://user-images.githubusercontent.com/5492274/123193091-b7ff8c00-d4d6-11eb-8d20-d983c1cb844f.png)

**Comment by tinohager** [comment]
is fixed line was commented out
