### ISSUE TITLE
Font size calculation to pass into ZPL

### ISSUE THREAD

**Issue by Karthik-Nagendiran** [BinaryKits/ZPLUtility#3]
I want to specify the font height and width which I'm setting in my windows applications for Label Elements. As of now I'm converting the font size as below.
font = new ZPLFont(fontWidth:0, fontHeight: (203 / 96) * (int) control.Font.SizeInPoints);
I'm scaling the ZPL elements from screen resolution DPI i.e 96 to Printer resolution DPI i.e 203.
The scaling is done properly and the output is also fine when I view it in Labelary viewer online.
But when it gets printed in the Zebra printer, the font sizes are not fitting into the Label dimension.
Given below the sample ZPL:
Label Dimension : 1.2 x 1.0 - 203 DPI

^XA
^CI28
^MMT
^PW220
^LS0
^FX ''1.2 x 1.0 Blank''
^FO106,15  ^A0N,25,25 ^FH^FD@Title@^FS
^FO10,49 ^A0N,24,0  ^FH^FD@Prepped@^FS
^FO10,76 ^A0N,24,0 ^FH^FD@Opened@^FS
^FO10,106 ^A0N,26,0 ^FH^FD@SDate@^FS
^FO120,106 ^A0N,26,0  ^FH^FD@STime@^FS
^FO10,137 ^A0N,24,0 ^FH^FD@Discard@^FS
^FO10,167 ^A0N,26,0  ^FH^FD@EDate@^FS
^FO120,167 ^A0N,26,0  ^FH^FD@ETime@^FS
^PQ
^XZ
The above command looks fine in Labelary viewer. But when printed it is not proper.
Any thoughts ?
thanks.
NK

**Comment by YipingRuan** [comment]
Can you try to describe what exactly is "not proper"? I can't see anything wrong with the ZPL code and Labelary viewer.  Do you think it is a hardware specific issue?

**Comment by YipingRuan** [comment]
I notice you set 0 for the font width, I think it should be same as the height?

**Comment by Karthik-Nagendiran** [comment]
Setting the width also didn't resolve the issue. I have to reduce the font size by few points and then send it to ZPL utility. Say for example if the font size is set to Arial 12pt, I have to reduce it by 5 points (for all font sizes which are >10). Now the printer is printing the Label within the Label dimension.

**Comment by YipingRuan** [comment]
I think not font can be scaled smoothly, can you try to test with an text array like:

```
^FO10,15^A0N,20,20 ^FH^FD@Title@^FS
^FO10,25^A0N,21,21 ^FH^FD@Title@^FS
^FO10,35^A0N,22,22 ^FH^FD@Title@^FS
.....
```
Compare from the labelary with your printed result?
