### ISSUE TITLE
Parsing string to ZPL Elements

### ISSUE THREAD

**Issue by Karthik-Nagendiran** [BinaryKits/ZPLUtility#4]
How can I reverse parse the ZPL string to corresponding list of Label Elements ? OR 
How can I load a ZPL string which will be converted to corresponding Label Elements?
I have a ZPL string in which I have to modify the Y - coordinates of all elements Field Origin.
Once modified I want to scale it to the desired DPI.

**Comment by YipingRuan** [comment]
You can't convert the ZPL code back to the C# objects.

This tool is to help generating the ZPL code, how can it be useful when you already have the ZPL code? If you plan to mix some raw ZPL content, you can use the "AddRawZPLCode" method.

**Comment by tinohager** [comment]
@Karthik-Nagendiran With the [CommandAnalyzers](https://github.com/BinaryKits/BinaryKits.Zpl/tree/master/src/BinaryKits.Zpl.Viewer/CommandAnalyzers) we have this logic now
