### ISSUE TITLE
Setting label home position

### ISSUE THREAD

**Issue by travisterrell** [BinaryKits/ZPLUtility#6]
By default, printing the generated ZPL string will generally result in an off-center label. Setting the label home position to 0,0 fixes this issue. 

I submitted a pull request to add `^LH0,0` to the reset string, as generally it is good practice to set this when initializing. I realize that one could instead add `ZPLRaw("^LH0,0"),` to the element list before the other label elements. However, if we go ahead and put this as default, it will be more friendly to most users, and more advanced users can still override this position, if needed, by adding it to the label list.

If you decide not to merge the request, though, maybe it would be a good idea to add it to the README.md?

Regards,
Travis

**Comment by YipingRuan** [comment]
Thanks for your attention! I want to discuss more before accepting the pull request.

Do you think it is useful to add another element type to express the ^LH? Or the raw will be good enough?

**Comment by travisterrell** [comment]
No problem! I don't think we would need to make another element type. As far as I can tell, the command should only be issued at the beginning of the print, then all other positioning made based on this initial home position. For what it's worth, here's a page with some more information on the command. [https://km.zebra.com/kb/index?page=content&id=SO8797](url) I'm no expert on ZPL, but it seems 99% of people will just need the default home position of 0,0.

Let me know what you think. If you think we need a new element of some kind, I'll be glad to code it, but I think the raw string should be sufficient. (Also: thanks for making this library! I've found it very useful in a project I'm working on.)

**Comment by YipingRuan** [comment]
Using raw ZPL disallows the possibility to do "Auto scaling based on different DPI".  But ^LH is for hardware control, and I guess nobody need auto scaling for the offset value between 2 different printers. (And maybe as you said 99% will just use 0,0). Yes Raw ZPL should be okay.

Do you think it works for you if I add a bool (UseDefaultLabelHome,  with default value true) in ZPLRenderOptions class to control the auto inserting of ^LH after ^XA(as your pull request https://github.com/BinaryKits/ZPLUtility/pull/5/commits/8739e57e91ec766ceb84a5f8959c42989a07cb51)?

**Comment by travisterrell** [comment]
Ah, didn't notice that would interfere. Yes, I think the bool would be a good idea. Go for it!

**Comment by YipingRuan** [comment]
Review https://github.com/BinaryKits/ZPLUtility/commit/7b9c8ea9312a5b81db6bb1c211ce6e2ec8786864

**Comment by travisterrell** [comment]
That looks good and clean! I'll close this.
