### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Linhngg** [BinaryKits/ZPLUtility#7]
Hello,

Im new to Zpl and this ZplUtility. Is there any available documentation of ZplUtility apart from examples in Readme.md file.

**Comment by YipingRuan** [comment]
Sorry nope.

This is an utility like HTML Helpers In ASP.NET MVC. You need to be able to write raw ZPL code first. Try to follow the ZPL document and play at http://labelary.com/viewer.html

Let me know if you need additional ZPL compnent being added.

**Comment by Linhngg** [comment]
I have no experience in ZPL code. I want to create ZPL code for label printing application.

If I know the detail (Field, Value, Position, etc)of the label I want to print, can I use your ZPLUtility to generate Zpl string?

I think it should be ok base on what I see in given examples. Just wondering why ability to write raw ZPL is needed?

**Comment by YipingRuan** [comment]
Sure, this tool is designed to handle the situation you mentioned. It is easier to use C# class than build the string yourself. 

While it works for most of the cases, sometimes you need to insert raw ZPL which is not included yet (like some control ZPL commands "^JW Set Ribbon Tension").
