### ISSUE TITLE
Text Field Rotate 

### ISSUE THREAD

**Issue by Linhngg** [BinaryKits/ZPLUtility#8]
Is it possible to specify text field rotation? I want to display a text field vertically (rotate 90 degree)

Is current library support this?

**Comment by YipingRuan** [comment]
I think you can control at the "ZPLFont" object.

`new ZPLFont(30, 30, "0", ZPLConstants.Orientation.Rotated90)`

**Comment by Linhngg** [comment]
Worked like charm. Thank you so much!
