### ISSUE TITLE
Viewer - UPS zpl label only show layout

### ISSUE THREAD

**Issue by ytcitsupport-jlin** [BinaryKits/ZPLUtility#83]
Hi I try to use the package to convert zpl label from UPS to image file (png)

But I only got the layout of the label

`string encodedLabel = "Cl5YQQ0KXkxSTg0KXk1OWQ0KXk1GTixODQpeTEgxMCwxMg0KXk1DWQ0KXlBPSQ0KXlBXODEyDQpeQ0kyNw0KXkZPMjg0LDUyNF5CWTNeQkNOLDEwNyxOLE4sTixBXkZWNDIwOTExMDFeRlMNCl5GTzY2LDc5Ml5CWTNeQkNOLDIwOCxOLE4sTixBXkZWMVpSNUYxODcwMzkxMTU3NTc4XkZTDQpeRk8yMCw0MzFeQ1ZZXkJEMl5GSF9eRkQwMDM4NDA5MTEwMTAwMDBbKT5fMUUwMV8xRDk2MVo5MTE1NzU3OF8xRFVQU05fMURSNUYxODdfMUUwN1FQJEZXJl8xQ18xQys2IC9GV18xREw5VjRVIjQ6VigvL0FPUVNGQlglMk8vWiNOQydTXzBEXzFFXzA0XkZTDQpeRk8xNSw3XkEwTiwyMCwyNF5GVkFUVEVOVElPTk5BTUVeRlMNCl5GTzE1LDI3XkEwTiwyMCwyNF5GVjEyMzQ1Njc4OTBeRlMNCl5GTzE1LDQ3XkEwTiwyMCwyNF5GVlNISVBQRVJOQU1FXkZTDQpeRk8xNSw2N15BME4sMjAsMjReRlYxMDU1IFcuIFZJQ1RPUklBIFNULl5GUw0KXkZPMTUsODdeQTBOLDIwLDI0XkZWQ09NUFRPTiAgQ0EgOTAyMjBeRlMNCl5GTzE1LDE0Ml5BME4sMjgsMzJeRlZTSElQIFRPOiBeRlMNCl5GTzYxLDE2Nl5BME4sMjgsMzJeRlZBVFRFTlRJT05OQU1FXkZTDQpeRk82MSwxOTReQTBOLDI4LDMyXkZWMTIzNDU2Nzg5MF5GUw0KXkZPNjEsMjIyXkEwTiwyOCwzMl5GVlNISVBUT05BTUVeRlMNCl5GTzYxLDI1MV5BME4sMjgsMzJeRlZXIFZJQ1RPUklBIFNULl5GUw0KXkZPNjEsMjc5XkEwTiw0NSw0NF5GVkNPTVBUT04gIENBICA5MTEwMV5GUw0KXkZPNDQ2LDleQTBOLDMwLDM0XkZWMjAgTEJTXkZTDQpeRk82ODMsOV5BME4sMjgsMzJeRlYxIE9GIDFeRlMNCl5GTzI2OSw0MzZeQTBOLDgwLDcwXkZWQ0EgOTAxIDktMTNeRlMNCl5GTzEwLDEwMzFeQTBOLDIyLDI2XkZWQklMTElORzogUC9QXkZTDQpeRk8xMCwxMTYzXkEwTiwyMiwyNl5GVlRyeCBSZWYgTm8uOiAyNzY1ODM1NTA5NzJeRlMNCl5GTzE3NSwxMjAzXkEwTiwxNCwyMF5GVlhPTCAyMS4xMC4wMyAgICAgICAgICBOVjQ1IDQyLjBBIDEwLzIwMjEqXkZTDQpeRk85LDY3MF5BME4sNTYsNTheRlZVUFMgR1JPVU5EXkZTDQpeRk85LDczMV5BME4sMjYsMzBeRlZUUkFDS0lORyAjOiAxWiBSNUYgMTg3IDAzIDkxMTUgNzU3OF5GUw0KXkZPMjI0LDg1M15BME4sOTUsNzReRlZTQU1QTEVeRlMNCl5GTzY4OSw2NTBeR0IxMjQsMTI1LDEyNCxCLDBeRlMNCl5GTzAsNjQ4XkdCODExLDE0LDE0LEIsMF5GUw0KXkZPMCw0MjNeR0I4MTIsNCw0LEIsMF5GUw0KXkZPMjQ0LDQyM15HQjQsMjI1LDQsQiwwXkZTDQpeRk8wLDc3NF5HQjgxMiw1LDUsQiwwXkZTDQpeRk8wLDEwMTNeR0I4MTIsMTQsMTQsQiwwXkZTDQpeRk82MjksMTE0NwpeR0ZBLDAwOTY5LDAwOTY5LDAxOSxGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRjAwMDAwMDAwMA0KRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkYwMDAwMDAwMDANCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwDQpGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRjAwMDAwMDAwMA0KRjAwMDAwMDAwMDAwMDFGODAwMDAwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDAwMDAxRjgwMDAwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwM0Y4MUY4M0ZDMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMDNGODFGODNGQzAwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDBGRkY5RjlGRkYwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwRkZGOUY5RkZGMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMEZGRkZGRkZGRkMwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDBGRkZGRkZGRkZDMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwRjA3RkZGRjBGQzAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMEYwN0ZGRkYwRkMwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDBGQzFGRkZDM0YwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwRkMxRkZGQzNGMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMEZGRkZGRkZGRjAwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDBGRkZGRkZGRkYwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwM0ZGRkZGRkZDMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMDNGRkZGRkZGQzAwMDAwMDAwMEYwMDAwMDAwMDANCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwDQpGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRjAwMDAwMDAwMA0KRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkYwMDAwMDAwMDANCkYwMDAwMDAwMDAwMUZGRkZGMDAwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwMDFGRkZGRjAwMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMDAzRkZGOUZDMDAwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDAwM0ZGRjlGQzAwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwM0ZFMUY4N0ZDMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMDNGRTFGODdGQzAwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDBGRjgxRjgzRkYwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwRkY4MUY4M0ZGMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMEZFMDFGODAzRjAwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDBGRTAxRjgwM0YwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwRjAwMUY4MDBGMDAwMDAwMDAwRjAwMDAwMDAwMA0KRjAwMDAwMDAwMEYwMDFGODAwRjAwMDAwMDAwMEYwMDAwMDAwMDANCkYwMDAwMDAwMDAwMDAxRjgwMDAwMDAwMDAwMDBGMDAwMDAwMDAwDQpGMDAwMDAwMDAwMDAwMUY4MDAwMDAwMDAwMDAwRjBGRkRDMUMwMA0KRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkYwRkZEQzFDMDANCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDBDMUUzQzAwDQpGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRjAwQzFFM0MwMA0KRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkYwMEMxQTJDMDANCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDBDMUI2QzAwDQpGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRjAwQzFCNkMwMA0KMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMEMxQjZDMDANCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBDMTlDQzAwDQowMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwQzE5Q0MwMA0KMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMEMxOUNDMDANCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBDMTg4QzAwDQowMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMA0KMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDANCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwDQpeRE4NCl5YWg0K";
                string label = Base64Util.DecodeBase64(encodedLabel);

                IPrinterStorage printerStorage = new PrinterStorage();

                var analyzer = new ZplAnalyzer(printerStorage);
                var analyzeInfo = analyzer.Analyze(label);

                var drawer = new ZplElementDrawer(printerStorage);
                foreach (var labelInfo in analyzeInfo.LabelInfos)
                {
                    var imageData = drawer.Draw(labelInfo.ZplElements);
                    File.WriteAllBytes(tmpFile.Path, imageData);
                }`

![image](https://user-images.githubusercontent.com/82171601/137369283-c4ade729-5646-4226-ab4b-bab0df797b96.png)

**Comment by tinohager** [comment]
This commands are currently not supported
`^FV`, `^BD`, `^FH`, `^PW`, `^PO`, `^MC`, `^MF`, `^MN`

Your ZPL Code have also an unknown command
`^DN`
