### ISSUE TITLE
ZPLSingleLineFieldBlock - Line Space Value

### ISSUE THREAD

**Issue by Karthik-Nagendiran** [BinaryKits/ZPLUtility#9]
Hi,
When using ZPLSingleLineFieldBlock the line space values are not computed properly. The value 9999 is showing when it is added to the label element object but when the complete ZPL is returned from the render engine, it is having a value like 21143.

_^A0N,44,44^FO29,33^FB211,9999,21143,L,0^FH^FDEnter Text^FS_

The above is after getting the ZPL from render engine. I'm not able to identify from where it is getting this value.

Below is the code to add the above element.
_labelElements.Add(new ZPLSingleLineFieldBlock(labelText, control.Location.X, control.Location.Y, control.Width,font, txtJustification, ZPLTextField.NewLineConversionMethod.ToSpace, true, false));_

Could please let me know what is wrong with this?

thanks,
Karthik

**Comment by YipingRuan** [comment]
Let me think about it

**Comment by Karthik-Nagendiran** [comment]
I have set the source DPI as screen resolution i.e, 96 and target DPI as printer resolution i.e, 203.
As I have windows application where is label is designed and using your utility to generate the ZPL for the corresponding label designed in windows forms. Though the value 21143 is not creating any major issues, the printer is taking little more time to print the label and sometimes it is feeding blank labels after printing the label. Any suggestions ?

**Comment by YipingRuan** [comment]
Can you try to test ZPLFieldBlock with line space = 2500 and max LineCount =2

1. Does this still cause slowness on your actual printer?
2. Is the second line correctly hidden from the printing result?
